# Generated by Django 4.0.3 on 2022-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_comment_user_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
